package com.assessment.googlemapsdemo.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.assessment.googlemapsdemo.database.Place;

import com.assessment.googlemapsdemo.database.PlaceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig placeDaoConfig;

    private final PlaceDao placeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        placeDaoConfig = daoConfigMap.get(PlaceDao.class).clone();
        placeDaoConfig.initIdentityScope(type);

        placeDao = new PlaceDao(placeDaoConfig, this);

        registerDao(Place.class, placeDao);
    }
    
    public void clear() {
        placeDaoConfig.clearIdentityScope();
    }

    public PlaceDao getPlaceDao() {
        return placeDao;
    }

}
