package com.assessment.googlemapsdemo.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PLACE".
 */
@Entity
public class Place {

    @Id(autoincrement = true)
    private Long id;
    private long place_id;

    @NotNull
    private String name;

    @NotNull
    private String latitude;

    @NotNull
    private String longitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Place() {
    }

    public Place(Long id) {
        this.id = id;
    }

    @Generated
    public Place(Long id, long place_id, String name, String latitude, String longitude) {
        this.id = id;
        this.place_id = place_id;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPlace_id() {
        return place_id;
    }

    public void setPlace_id(long place_id) {
        this.place_id = place_id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getLatitude() {
        return latitude;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLatitude(@NotNull String latitude) {
        this.latitude = latitude;
    }

    @NotNull
    public String getLongitude() {
        return longitude;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLongitude(@NotNull String longitude) {
        this.longitude = longitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
